# Generated by Django 6.0.2 on 2026-06-27 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(blank=True, max_length=180)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('COORDINATOR', 'Coordinator'), ('VIEWER', 'Viewer')], default='COORDINATOR', max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('location', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active response'), ('STABILIZING', 'Stabilizing'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('location', models.CharField(max_length=240)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('triage', models.CharField(choices=[('RED', 'Immediate'), ('YELLOW', 'Urgent'), ('GREEN', 'Lower urgency'), ('BLACK', 'Expectant / deceased'), ('UNKNOWN', 'Not assessed')], default='UNKNOWN', max_length=10)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('VERIFIED', 'Verified'), ('IN_PROGRESS', 'Response underway'), ('RESOLVED', 'Resolved')], default='REPORTED', max_length=20)),
                ('people_affected', models.PositiveIntegerField(default=0)),
                ('people_trapped', models.PositiveIntegerField(default=0)),
                ('hazards', models.CharField(blank=True, max_length=300)),
                ('details', models.TextField(blank=True)),
                ('reporter_name', models.CharField(blank=True, max_length=120)),
                ('reporter_contact', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_emergencies', to='coordination.member')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencies', to='coordination.situation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='coordination.situation'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('COORDINATOR', 'Coordinator'), ('VIEWER', 'Viewer')], default='COORDINATOR', max_length=20)),
                ('intended_for', models.CharField(blank=True, max_length=120)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invitations', to='coordination.member')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='coordination.situation')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='coordination.member')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='coordination.situation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('organization', models.CharField(blank=True, max_length=140)),
                ('specialty', models.CharField(choices=[('SEARCH_RESCUE', 'Search & rescue'), ('MEDICAL', 'Medical'), ('FIRE', 'Fire & hazmat'), ('ENGINEERING', 'Structural engineering'), ('LOGISTICS', 'Logistics'), ('SECURITY', 'Security'), ('OTHER', 'Other')], default='SEARCH_RESCUE', max_length=30)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('DEPLOYED', 'Deployed'), ('RESTING', 'Resting'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('people_count', models.PositiveSmallIntegerField(default=1)),
                ('leader_name', models.CharField(blank=True, max_length=120)),
                ('contact', models.CharField(blank=True, max_length=180)),
                ('current_location', models.CharField(blank=True, max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='coordination.situation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='coordination.emergency')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coordination.member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='coordination.team')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emergency',
            index=models.Index(fields=['situation', 'status', 'triage'], name='coordinatio_situati_8ae5c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('situation', 'name'), name='unique_team_name_per_situation'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('team',), name='one_active_assignment_per_team'),
        ),
    ]
