# Generated by Django 6.0.2 on 2026-06-27 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='source',
            field=models.CharField(choices=[('PUBLIC', 'Public report'), ('COORDINATOR', 'Coordinator report')], default='COORDINATOR', max_length=20),
        ),
        migrations.AddField(
            model_name='situation',
            name='public_reporting_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_emergencies', to='coordination.member'),
        ),
    ]
