# Generated by Django 6.0.2 on 2026-06-27 17:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0002_emergency_source_situation_public_reporting_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Supplies needed', max_length=180)),
                ('delivery_location', models.CharField(max_length=240)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('details', models.TextField(blank=True)),
                ('requester_name', models.CharField(blank=True, max_length=120)),
                ('requester_contact', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partially covered'), ('COVERED', 'Fully covered'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_requests', to='coordination.situation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(choices=[('UNIT', 'units'), ('KG', 'kg'), ('LITER', 'liters'), ('BOX', 'boxes'), ('PACK', 'packs'), ('PALLET', 'pallets')], default='UNIT', max_length=20)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coordination.supplyrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SupplyCommitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contributor_name', models.CharField(max_length=120)),
                ('contributor_contact', models.CharField(blank=True, max_length=180)),
                ('origin_location', models.CharField(blank=True, max_length=240)),
                ('origin_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origin_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_location', models.CharField(blank=True, max_length=240)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLEDGED', 'Preparing'), ('IN_TRANSIT', 'In transit'), ('ARRIVED', 'Arrived'), ('CANCELLED', 'Cancelled')], default='PLEDGED', max_length=20)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('share_live_location', models.BooleanField(default=False)),
                ('tracking_token_hash', models.CharField(max_length=64, unique=True)),
                ('last_location_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='coordination.supplyrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyCommitmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coordination.supplycommitment')),
                ('supply_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_items', to='coordination.supplyitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('commitment', 'supply_item'), name='unique_item_per_supply_commitment')],
            },
        ),
    ]
