# Generated by Django 6.0.2 on 2026-06-27 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0003_supplyrequest_supplyitem_supplycommitment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='source',
            field=models.CharField(choices=[('PUBLIC', 'Public report'), ('COORDINATOR', 'Coordinator report'), ('MISSING_PERSON', 'Missing person report')], default='COORDINATOR', max_length=20),
        ),
        migrations.CreateModel(
            name='MissingPersonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=160)),
                ('approximate_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('physical_description', models.TextField(blank=True)),
                ('clothing', models.CharField(blank=True, max_length=300)),
                ('circumstances', models.TextField(blank=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emergency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='missing_person', to='coordination.emergency')),
            ],
        ),
    ]
