# Generated by Django 6.0.2 on 2026-06-27 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0004_alter_emergency_source_missingpersonreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('page_url', models.URLField(blank=True, max_length=500)),
                ('locale', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='situation',
            name='codename',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='source',
            field=models.CharField(choices=[('PUBLIC', 'Public report'), ('COORDINATOR', 'Coordinator report'), ('MISSING_PERSON', 'Missing person report'), ('EXTERNAL_FEED', 'External feed')], default='COORDINATOR', max_length=20),
        ),
        migrations.CreateModel(
            name='FeedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('source_url', models.URLField(max_length=500)),
                ('api_url', models.URLField(blank=True, max_length=500)),
                ('adapter', models.CharField(choices=[('VENEZUELA_MISSING', 'Venezuela missing people'), ('GENERIC_JSON', 'Generic JSON')], max_length=40)),
                ('enabled', models.BooleanField(default=False)),
                ('authorization_header', models.CharField(blank=True, max_length=300)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_sources', to='coordination.situation')),
            ],
        ),
        migrations.CreateModel(
            name='FeedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=180)),
                ('content_hash', models.CharField(max_length=64)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('raw_payload', models.JSONField(default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('emergency', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_record', to='coordination.emergency')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='coordination.feedsource')),
            ],
        ),
        migrations.CreateModel(
            name='MagicLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_logins', to='coordination.member')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_logins', to='coordination.situation')),
            ],
        ),
        migrations.CreateModel(
            name='MemberAccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_keys', to='coordination.member')),
            ],
        ),
        migrations.AddConstraint(
            model_name='feedsource',
            constraint=models.UniqueConstraint(fields=('situation', 'source_url'), name='unique_feed_source_per_situation'),
        ),
        migrations.AddConstraint(
            model_name='feedrecord',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_external_feed_record'),
        ),
    ]
