# Generated by Django 5.2.10 on 2026-08-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0007_emergency_structural_fields_and_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('GDACS', 'GDACS'), ('USGS', 'USGS'), ('EONET', 'NASA EONET')], max_length=10)),
                ('external_id', models.CharField(max_length=180)),
                ('event_type', models.CharField(choices=[('EARTHQUAKE', 'Earthquake'), ('CYCLONE', 'Tropical cyclone'), ('FLOOD', 'Flood'), ('VOLCANO', 'Volcanic activity'), ('WILDFIRE', 'Wildfire'), ('SEVERE_STORM', 'Severe storm'), ('DROUGHT', 'Drought'), ('OTHER', 'Other hazard')], default='OTHER', max_length=20)),
                ('alert_level', models.CharField(choices=[('GREEN', 'Green'), ('ORANGE', 'Orange'), ('RED', 'Red'), ('UNKNOWN', 'Unclassified')], default='UNKNOWN', max_length=10)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=160)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('severity_value', models.FloatField(blank=True, null=True)),
                ('severity_unit', models.CharField(blank=True, max_length=20)),
                ('population_affected', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('event_from', models.DateTimeField(blank=True, null=True)),
                ('event_to', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['event_type', 'is_active'], name='coordinatio_event_t_cdf373_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_world_event')],
            },
        ),
    ]
